services:

  mysql:
    image: mysql:8.0
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: MangaTranslationSystem
      MYSQL_USER: Admin
      MYSQL_PASSWORD: Admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-alpine        
    restart: always
    ports:
      - "5672:5672"                 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    env_file: .env
    command: > 
        sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy

  celery:
    build:
      context: .
      dockerfile: celery.dockerfile              
    restart: always
    cap_add:
      - SYS_PTRACE
    shm_size: '7gb'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy


volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:

networks:
  MyNetwork:
    driver: bridge